### ISSUE TITLE
Lack of pre-training models

### ISSUE THREAD

**Issue by jiepainanhai** [Datasciensyash/SeismicNet#1]
when I try to run this code ,it gave me an error:
 NO such file: pretrained checkpoints/U - NET - BS - 5. Torch '
![image](https://user-images.githubusercontent.com/90892226/167984783-16369f6a-a989-46c2-b2df-0645c3c57e9e.png)

**Comment by Datasciensyash** [comment]
It seems i figured out what's wrong. Try to checkout to `fix_bug ` branch and reproduce

**Comment by Datasciensyash** [comment]
Closing issue
